# Generated by Django 3.0.4 on 2020-06-03 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='session_string',
            new_name='session_str',
        ),
    ]
