# Generated by Django 3.0.4 on 2020-06-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200603_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='session_str',
            field=models.UUIDField(default='118b89e1457441e7829ba4ccb2c7737a', editable=False, unique=True),
        ),
    ]
