# Generated by Django 3.0.4 on 2020-06-03 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_auto_20200603_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatline',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='session_str',
            field=models.UUIDField(default='ea77daabe18d4a3fbbcaa9b712deba88', editable=False, unique=True),
        ),
    ]
